<?php

namespace ContainerO1tQihN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1winx9YService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private '.service_locator.1winx9Y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1winx9Y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'contao_failure' => ['privates', 'messenger.transport.contao_failure', 'getMessenger_Transport_ContaoFailureService', true],
            'contao_prio_high' => ['privates', 'messenger.transport.contao_prio_high', 'getMessenger_Transport_ContaoPrioHighService', true],
            'contao_prio_high_doctrine' => ['privates', 'messenger.transport.contao_prio_high_doctrine', 'getMessenger_Transport_ContaoPrioHighDoctrineService', true],
            'contao_prio_low' => ['privates', 'messenger.transport.contao_prio_low', 'getMessenger_Transport_ContaoPrioLowService', true],
            'contao_prio_low_doctrine' => ['privates', 'messenger.transport.contao_prio_low_doctrine', 'getMessenger_Transport_ContaoPrioLowDoctrineService', true],
            'contao_prio_normal' => ['privates', 'messenger.transport.contao_prio_normal', 'getMessenger_Transport_ContaoPrioNormalService', true],
            'contao_prio_normal_doctrine' => ['privates', 'messenger.transport.contao_prio_normal_doctrine', 'getMessenger_Transport_ContaoPrioNormalDoctrineService', true],
            'messenger.transport.contao_failure' => ['privates', 'messenger.transport.contao_failure', 'getMessenger_Transport_ContaoFailureService', true],
            'messenger.transport.contao_prio_high' => ['privates', 'messenger.transport.contao_prio_high', 'getMessenger_Transport_ContaoPrioHighService', true],
            'messenger.transport.contao_prio_high_doctrine' => ['privates', 'messenger.transport.contao_prio_high_doctrine', 'getMessenger_Transport_ContaoPrioHighDoctrineService', true],
            'messenger.transport.contao_prio_low' => ['privates', 'messenger.transport.contao_prio_low', 'getMessenger_Transport_ContaoPrioLowService', true],
            'messenger.transport.contao_prio_low_doctrine' => ['privates', 'messenger.transport.contao_prio_low_doctrine', 'getMessenger_Transport_ContaoPrioLowDoctrineService', true],
            'messenger.transport.contao_prio_normal' => ['privates', 'messenger.transport.contao_prio_normal', 'getMessenger_Transport_ContaoPrioNormalService', true],
            'messenger.transport.contao_prio_normal_doctrine' => ['privates', 'messenger.transport.contao_prio_normal_doctrine', 'getMessenger_Transport_ContaoPrioNormalDoctrineService', true],
            'messenger.transport.sync' => ['privates', 'messenger.transport.sync', 'getMessenger_Transport_SyncService', true],
            'sync' => ['privates', 'messenger.transport.sync', 'getMessenger_Transport_SyncService', true],
        ], [
            'contao_failure' => '?',
            'contao_prio_high' => '?',
            'contao_prio_high_doctrine' => '?',
            'contao_prio_low' => '?',
            'contao_prio_low_doctrine' => '?',
            'contao_prio_normal' => '?',
            'contao_prio_normal_doctrine' => '?',
            'messenger.transport.contao_failure' => '?',
            'messenger.transport.contao_prio_high' => '?',
            'messenger.transport.contao_prio_high_doctrine' => '?',
            'messenger.transport.contao_prio_low' => '?',
            'messenger.transport.contao_prio_low_doctrine' => '?',
            'messenger.transport.contao_prio_normal' => '?',
            'messenger.transport.contao_prio_normal_doctrine' => '?',
            'messenger.transport.sync' => '?',
            'sync' => '?',
        ]);
    }
}
