<?php

namespace ContainerO1tQihN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_Messenger_AutoFallbackTransportFactoryService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'contao.messenger.auto_fallback_transport_factory' shared service.
     *
     * @return \Contao\CoreBundle\Messenger\Transport\AutoFallbackTransportFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/TransportFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Messenger/Transport/AutoFallbackTransportFactory.php';

        $a = ($container->privates['contao.messenger.auto_fallback_notifier'] ?? $container->load('getContao_Messenger_AutoFallbackNotifierService'));

        if (isset($container->privates['contao.messenger.auto_fallback_transport_factory'])) {
            return $container->privates['contao.messenger.auto_fallback_transport_factory'];
        }
        $b = ($container->privates['messenger.receiver_locator'] ?? $container->load('getMessenger_ReceiverLocatorService'));

        if (isset($container->privates['contao.messenger.auto_fallback_transport_factory'])) {
            return $container->privates['contao.messenger.auto_fallback_transport_factory'];
        }

        return $container->privates['contao.messenger.auto_fallback_transport_factory'] = new \Contao\CoreBundle\Messenger\Transport\AutoFallbackTransportFactory($a, $b);
    }
}
