<?php

namespace ContainerO1tQihN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_Messenger_AutoFallbackNotifierService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'contao.messenger.auto_fallback_notifier' shared service.
     *
     * @return \Contao\CoreBundle\Messenger\AutoFallbackNotifier
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Messenger/AutoFallbackNotifier.php';

        $a = ($container->privates['messenger.receiver_locator'] ?? $container->load('getMessenger_ReceiverLocatorService'));

        if (isset($container->privates['contao.messenger.auto_fallback_notifier'])) {
            return $container->privates['contao.messenger.auto_fallback_notifier'];
        }

        return $container->privates['contao.messenger.auto_fallback_notifier'] = new \Contao\CoreBundle\Messenger\AutoFallbackNotifier(($container->services['cache.app'] ?? $container->load('getCache_AppService')), $a);
    }
}
