<?php

namespace ContainerO1tQihN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_Retry_SendFailedMessageForRetryListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'messenger.retry.send_failed_message_for_retry_listener' shared service.
     *
     * @return \Symfony\Component\Messenger\EventListener\SendFailedMessageForRetryListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/EventListener/SendFailedMessageForRetryListener.php';

        $a = ($container->privates['.service_locator.1winx9Y'] ?? $container->load('get_ServiceLocator_1winx9YService'));

        if (isset($container->privates['messenger.retry.send_failed_message_for_retry_listener'])) {
            return $container->privates['messenger.retry.send_failed_message_for_retry_listener'];
        }
        $b = ($container->privates['monolog.logger.messenger'] ?? $container->load('getMonolog_Logger_MessengerService'));

        if (isset($container->privates['messenger.retry.send_failed_message_for_retry_listener'])) {
            return $container->privates['messenger.retry.send_failed_message_for_retry_listener'];
        }
        $c = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['messenger.retry.send_failed_message_for_retry_listener'])) {
            return $container->privates['messenger.retry.send_failed_message_for_retry_listener'];
        }

        return $container->privates['messenger.retry.send_failed_message_for_retry_listener'] = new \Symfony\Component\Messenger\EventListener\SendFailedMessageForRetryListener($a, new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'contao_failure' => ['privates', 'messenger.retry.multiplier_retry_strategy.contao_failure', 'getMessenger_Retry_MultiplierRetryStrategy_ContaoFailureService', true],
            'contao_prio_high' => ['privates', 'messenger.retry.multiplier_retry_strategy.contao_prio_high', 'getMessenger_Retry_MultiplierRetryStrategy_ContaoPrioHighService', true],
            'contao_prio_high_doctrine' => ['privates', 'messenger.retry.multiplier_retry_strategy.contao_prio_high_doctrine', 'getMessenger_Retry_MultiplierRetryStrategy_ContaoPrioHighDoctrineService', true],
            'contao_prio_low' => ['privates', 'messenger.retry.multiplier_retry_strategy.contao_prio_low', 'getMessenger_Retry_MultiplierRetryStrategy_ContaoPrioLowService', true],
            'contao_prio_low_doctrine' => ['privates', 'messenger.retry.multiplier_retry_strategy.contao_prio_low_doctrine', 'getMessenger_Retry_MultiplierRetryStrategy_ContaoPrioLowDoctrineService', true],
            'contao_prio_normal' => ['privates', 'messenger.retry.multiplier_retry_strategy.contao_prio_normal', 'getMessenger_Retry_MultiplierRetryStrategy_ContaoPrioNormalService', true],
            'contao_prio_normal_doctrine' => ['privates', 'messenger.retry.multiplier_retry_strategy.contao_prio_normal_doctrine', 'getMessenger_Retry_MultiplierRetryStrategy_ContaoPrioNormalDoctrineService', true],
            'sync' => ['privates', 'messenger.retry.multiplier_retry_strategy.sync', 'getMessenger_Retry_MultiplierRetryStrategy_SyncService', true],
        ], [
            'contao_failure' => '?',
            'contao_prio_high' => '?',
            'contao_prio_high_doctrine' => '?',
            'contao_prio_low' => '?',
            'contao_prio_low_doctrine' => '?',
            'contao_prio_normal' => '?',
            'contao_prio_normal_doctrine' => '?',
            'sync' => '?',
        ]), $b, $c);
    }
}
